import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "./globals.css";

const firaSans = Fira_Sans({ subsets: ["latin"], weight: '400' });

export const metadata: Metadata = {
  title: "Housemates blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={firaSans.className}>
        {children}
      </body>
    </html>
  );
}

